version: '3.4'

services:

  ################ Catalog ###################
  
  catalogdb: #catalog database port 27017
    container_name: catalogdb
    ports:
      -  "27017:27017"
    restart: always
    volumes:
      -  catalogdb_data:/data/db #save data in mongodb
  
  manageMongo: #this container for manage mongodb port 3000
    container_name: manageMongo
    ports:
      - "3000:3000"
    depends_on:
      - catalogdb
    volumes:
      - manageMongo:/data/db

  catalog.api: #port 8000
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017" #from appsettings.json and override
    ports:
      - "8000:80"
    depends_on:
       - catalogdb
  
  ################ Basket #####################
       
  basketdb: #basket database port 6379
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - basketdb_data:/data  

  manageRedis: #this container for manage redis port 8081
    container_name: manageRedis
    environment:
      - REDIS_HOSTS=local:basketdb:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - 8081:8081
    depends_on:
      - basketdb
      
  basket.api: #port 8001
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConfigurationRedis:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80"
      
  ################ Discount #####################
  
  discountdb: #discount db port 5432
    container_name: discountdb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=DiscountDb
    restart: always
    volumes:
      - discountdb_data:/var/lib/postgresql/data/

  managePostgres: #manage postgres port 5050
    container_name: managePostgres
    depends_on:
      - discountdb
    ports:
      - 5050:80
    restart: always
    volumes:
      - managePostgres:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      
  discount.api: #PORT 8002
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin;"
    ports:
      - "8002:80"
    depends_on:
      - discountdb