version: '3.4'

services:

  ################# Catalog ##################
  
  catalogdb:
    image: mongo
  
  manageMongo:
    image: mongoclient/mongoclient

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  ################# Basket ##################
      
  basketdb:
    image: redis

  manageRedis:
    image: rediscommander/redis-commander:latest

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  ################ Discount with GRPC #####################
  
  discountdb:
    image: postgres

  managePostgres:
    image: dpage/pgadmin4
    
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/discount/Discount.Grpc/Dockerfile

  ################ Ordering #####################
  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  order.api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Services/Ordering/API/Dockerfile
  
  ################ RabbitMQ #####################

  rabbitmq:
    image: rabbitmq:3-management-alpine
  
volumes:
  catalogdb_data:
  manageMongo:
  basketdb_data:
  discountdb_data:
  managePostgres: