version: '3.4'

services:

  ################ Catalog ###################
  
  catalogdb: #Port 27017
    container_name: catalogdb
    ports:
      -  "27017:27017"
    restart: always
    volumes:
      -  catalogdb_data:/data/db #save data in mongodb
  
  manageMongo: #Port 3000
    container_name: manageMongo
    ports:
      - "3000:3000"
    depends_on:
      - catalogdb
    volumes:
      - manageMongo:/data/db

  catalog.api: #Port 8000
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017" #from appsettings.json and override
    ports:
      - "8000:80"
    depends_on:
       - catalogdb
  
  ################ Basket #####################
       
  basketdb: #Port 6379
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379
    volumes:
      - basketdb_data:/data  

  manageRedis: #Port 8081
    container_name: manageRedis
    environment:
      - REDIS_HOSTS=local:basketdb:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - 8081:8081
    depends_on:
      - basketdb
      
  basket.api: #Port 8001
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConfigurationRedis:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
    depends_on:
      - basketdb #it is container
    ports:
      - "8001:80"
      
  ################ Discount with GRPC #####################
  
  discountdb: #Port 5432
    container_name: discountdb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=DiscountDb
    restart: always
    volumes:
      - discountdb_data:/var/lib/postgresql/data/

  managePostgres: #Port 5050
    container_name: managePostgres
    depends_on:
      - discountdb
    ports:
      - 5050:80
    restart: always
    volumes:
      - managePostgres:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      
  discount.api: #Port 8002
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin;"
    ports:
      - "8002:80"
    depends_on:
      - discountdb
      
  discount.grpc: #Port 8003
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin;"
    depends_on : 
      - discountdb
    ports:
      - "8003:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ################ Ordering #####################

  orderdb: #Port 1433
    container_name: orderdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  order.api: #Port 8004
    container_name: order.api
    depends_on :
      - orderdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;"
    ports:
      - "8004:80"

  ################# RabbitMQ #####################

  rabbitmq: #Port : 5672,15672
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672