version: '3.4'

services:

  #################Catalog##################
  
  catalogdb:
    image: mongo
  
  manageMongo:
    image: mongoclient/mongoclient

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  #################Basket##################
      
  basketdb:
    image: redis

  manageRedis:
    image: rediscommander/redis-commander:latest

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  catalogdb_data:
  manageMongo:
  basketdb_data: